import {
  Entity,
  PrimaryGeneratedColumn,
  Column,
  ManyToOne,
  OneToMany,
  JoinColumn,
  CreateDateColumn,
  UpdateDateColumn,
  Index,
} from 'typeorm';
import { Tenant } from './tenant.entity';
import { User } from './user.entity';
import { OrderItem } from './order-item.entity';

export enum OrderStatus {
  PENDING = 'pending',       // created, not yet paid
  PAID = 'paid',             // payment confirmed
  REFUNDED = 'refunded',     // full refund issued
  PARTIAL_REFUND = 'partial_refund',
  VOID = 'void',             // cancelled before payment
}

export enum PaymentMethod {
  CASH = 'cash',
  CARD = 'card',
  MIXED = 'mixed',       // partial cash + partial card
}

/**
 * Order (sale) entity.
 *
 * Index strategy:
 *   - (tenantId) — all order queries are tenant-scoped
 *   - (tenantId, status) — reporting filters by status
 *   - (tenantId, createdAt) — chronological listing, reporting
 *   - (tenantId, cashierId) — per-cashier reports
 *   - offlineSyncId — unique per-tenant offline reconciliation key
 *
 * Money fields (subtotal, tax, total, ...) are integer cents, same as Product.
 */
@Entity('orders')
@Index('idx_order_tenant', ['tenantId'])
@Index('idx_order_tenant_status', ['tenantId', 'status'])
@Index('idx_order_tenant_created', ['tenantId', 'createdAt'])
@Index('idx_order_tenant_cashier', ['tenantId', 'cashierId'])
@Index('idx_order_offline_sync', ['tenantId', 'offlineSyncId'], {
  unique: true,
  where: '"offline_sync_id" IS NOT NULL',
})
export class Order {
  @PrimaryGeneratedColumn('uuid')
  id: string;

  @Column({ type: 'uuid' })
  tenantId: string;

  @Column({ type: 'uuid', nullable: true })
  cashierId: string | null;

  /**
   * Human-readable order number for receipts, e.g. "ORD-00123".
   * Generated by the service, not the DB (to allow custom prefixes).
   */
  @Column({ type: 'varchar', length: 30 })
  orderNumber: string;

  @Column({ type: 'enum', enum: OrderStatus, default: OrderStatus.PENDING })
  status: OrderStatus;

  @Column({ type: 'enum', enum: PaymentMethod, nullable: true })
  paymentMethod: PaymentMethod | null;

  // ── Money ────────────────────────────────────────────────────────────
  @Column({ type: 'int' })
  subtotalCents: number; // sum of (item.unitPriceCents * qty)

  @Column({ type: 'int', default: 0 })
  discountCents: number;

  @Column({ type: 'int', default: 0 })
  taxCents: number;

  @Column({ type: 'int' })
  totalCents: number; // subtotal - discount + tax

  @Column({ type: 'int', default: 0 })
  cashTenderedCents: number; // how much cash the customer gave

  @Column({ type: 'int', default: 0 })
  changeCents: number;

  // ── Offline sync ───────────────────────────────────────────────────────
  /**
   * UUID generated by the POS client before the order is sent to the server.
   * Allows idempotent re-submission: if the network drops after the server
   * persisted but before the client received the response, the client can
   * safely retry without creating a duplicate.
   */
  @Column({ type: 'uuid', nullable: true })
  offlineSyncId: string | null;

  @Column({ type: 'timestamptz', nullable: true })
  offlineCreatedAt: Date | null; // when the sale actually occurred offline

  @Column({ type: 'text', nullable: true })
  notes: string | null;

  @CreateDateColumn({ type: 'timestamptz' })
  createdAt: Date;

  @UpdateDateColumn({ type: 'timestamptz' })
  updatedAt: Date;

  // ── Relations ──────────────────────────────────────────────────────────
  @ManyToOne(() => Tenant, (t) => t.orders, { onDelete: 'CASCADE' })
  @JoinColumn({ name: 'tenant_id' })
  tenant: Tenant;

  @ManyToOne(() => User, { onDelete: 'SET NULL', nullable: true })
  @JoinColumn({ name: 'cashier_id' })
  cashier: User | null;

  @OneToMany(() => OrderItem, (i) => i.order, { cascade: ['insert'] })
  items: OrderItem[];
}
