/**
 * Dexie (IndexedDB) schema for offline-first POS.
 *
 * Design decisions:
 * - Products table: full product catalogue cached locally; synced incrementally
 *   using the `version` cursor from the backend.
 * - PendingOrders table: orders created offline, queued for sync.
 *   Once successfully submitted they are NOT deleted — kept for local receipt
 *   history and moved to `syncedAt` state.
 * - SyncMeta: simple key/value store for sync state (last sync cursor, etc.)
 */
import Dexie, { Table } from 'dexie';

export interface LocalProduct {
  id: string;
  tenantId: string;
  categoryId: string | null;
  name: string;
  barcode: string | null;
  priceCents: number;
  taxRateBps: number;
  imageUrl: string | null;
  isActive: boolean;
  trackStock: boolean;
  stockQty: number;
  categoryName: string | null;
  version: number;
  updatedAt: string; // ISO string
}

export interface LocalCategory {
  id: string;
  tenantId: string;
  name: string;
  colorHex: string | null;
  sortOrder: number;
}

export type PendingOrderStatus =
  | 'pending'    // waiting for network
  | 'syncing'    // currently being submitted
  | 'synced'     // successfully submitted
  | 'failed';    // permanent failure after max retries

export interface PendingOrderItem {
  productId: string;
  productName: string;
  productBarcode: string | null;
  unitPriceCents: number;
  taxRateBps: number;
  quantity: number;
  discountCents: number;
  lineTotalCents: number;
}

export interface PendingOrder {
  // IndexedDB-assigned auto-increment key
  localId?: number;
  // UUID generated by client before submission — used as offlineSyncId
  syncId: string;
  tenantId: string;
  cashierId: string;
  status: PendingOrderStatus;
  paymentMethod: string;
  items: PendingOrderItem[];
  subtotalCents: number;
  discountCents: number;
  taxCents: number;
  totalCents: number;
  cashTenderedCents: number;
  changeCents: number;
  notes: string | null;
  createdAt: string;    // ISO — actual sale time
  syncedAt: string | null;
  retryCount: number;
  serverOrderId: string | null; // filled after successful sync
  serverOrderNumber: string | null;
  errorMessage: string | null;
}

export interface SyncMeta {
  key: string;
  value: string | number | null;
}

class PosDatabase extends Dexie {
  products!: Table<LocalProduct, string>;
  categories!: Table<LocalCategory, string>;
  pendingOrders!: Table<PendingOrder, number>;
  syncMeta!: Table<SyncMeta, string>;

  constructor() {
    super('hizlipos');

    this.version(1).stores({
      products:       'id, tenantId, categoryId, barcode, version, isActive',
      categories:     'id, tenantId, sortOrder',
      pendingOrders:  '++localId, syncId, status, createdAt',
      syncMeta:       'key',
    });
  }
}

export const db = new PosDatabase();

// ── Sync meta helpers ──────────────────────────────────────────────────────

export async function getSyncCursor(): Promise<number> {
  const meta = await db.syncMeta.get('productVersion');
  return typeof meta?.value === 'number' ? meta.value : 0;
}

export async function setSyncCursor(version: number): Promise<void> {
  await db.syncMeta.put({ key: 'productVersion', value: version });
}

export async function getLastSyncTime(): Promise<string | null> {
  const meta = await db.syncMeta.get('lastSyncTime');
  return typeof meta?.value === 'string' ? meta.value : null;
}

export async function setLastSyncTime(iso: string): Promise<void> {
  await db.syncMeta.put({ key: 'lastSyncTime', value: iso });
}
